app = 'signalforge-late-fire-4638'
primary_region = 'sin'

[build]
  builder = 'paketobuildpacks/builder-jammy-base'
  [build.env]
    BP_GO_TARGETS = "./cmd/app"
    BP_GO_BINARY_NAME = "signalforge"

[processes]
  app = './bin/signalforge -mode daily'
  daily = './bin/signalforge -mode daily'
  rebalance = './bin/signalforge -mode rebalance'
  dca = './bin/signalforge -mode dca'

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
