app = 'signalforge-late-fire-4638'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[processes]
  app = '/signalforge -mode daily'
  daily = '/signalforge -mode daily'
  rebalance = '/signalforge -mode rebalance'
  dca = '/signalforge -mode dca'

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
